version: '3.0'

volumes:
  db:

services:
  db:
    image: postgres:15.5-alpine
    container_name: db
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: localhost
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready-U ${PGSQL_USER}']
      interval: 30s